server:
  port: 9000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      
      routes:
        # Route for Auction & Bid REST API
        - id: bidmesh-backend-api
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
        
        # Route for WebSockets (Stomp/SockJS)
        - id: bidmesh-backend-ws
          uri: http://localhost:8080
          predicates:
            - Path=/ws-auction/**
